// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.13.0
// source: accident.proto

package proto

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type AccidentData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username  string               `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	CarId     string               `protobuf:"bytes,2,opt,name=car_id,json=carId,proto3" json:"car_id,omitempty"`
	Time      *timestamp.Timestamp `protobuf:"bytes,3,opt,name=time,proto3" json:"time,omitempty"`
	Latitude  float64              `protobuf:"fixed64,4,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude float64              `protobuf:"fixed64,5,opt,name=longitude,proto3" json:"longitude,omitempty"`
}

func (x *AccidentData) Reset() {
	*x = AccidentData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_accident_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AccidentData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccidentData) ProtoMessage() {}

func (x *AccidentData) ProtoReflect() protoreflect.Message {
	mi := &file_accident_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccidentData.ProtoReflect.Descriptor instead.
func (*AccidentData) Descriptor() ([]byte, []int) {
	return file_accident_proto_rawDescGZIP(), []int{0}
}

func (x *AccidentData) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *AccidentData) GetCarId() string {
	if x != nil {
		return x.CarId
	}
	return ""
}

func (x *AccidentData) GetTime() *timestamp.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

func (x *AccidentData) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *AccidentData) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

type CreateAccidentDataResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccidentId string `protobuf:"bytes,1,opt,name=accident_id,json=accidentId,proto3" json:"accident_id,omitempty"`
}

func (x *CreateAccidentDataResponse) Reset() {
	*x = CreateAccidentDataResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_accident_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateAccidentDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAccidentDataResponse) ProtoMessage() {}

func (x *CreateAccidentDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_accident_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAccidentDataResponse.ProtoReflect.Descriptor instead.
func (*CreateAccidentDataResponse) Descriptor() ([]byte, []int) {
	return file_accident_proto_rawDescGZIP(), []int{1}
}

func (x *CreateAccidentDataResponse) GetAccidentId() string {
	if x != nil {
		return x.AccidentId
	}
	return ""
}

var File_accident_proto protoreflect.FileDescriptor

var file_accident_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x61, 0x63, 0x63, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xab, 0x01, 0x0a, 0x0c, 0x41, 0x63, 0x63,
	0x69, 0x64, 0x65, 0x6e, 0x74, 0x44, 0x61, 0x74, 0x61, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65,
	0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65,
	0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x15, 0x0a, 0x06, 0x63, 0x61, 0x72, 0x5f, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x63, 0x61, 0x72, 0x49, 0x64, 0x12, 0x2e, 0x0a, 0x04,
	0x74, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08,
	0x6c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x01, 0x52, 0x08,
	0x6c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x6c, 0x6f, 0x6e, 0x67,
	0x69, 0x74, 0x75, 0x64, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x01, 0x52, 0x09, 0x6c, 0x6f, 0x6e,
	0x67, 0x69, 0x74, 0x75, 0x64, 0x65, 0x22, 0x3d, 0x0a, 0x1a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x41, 0x63, 0x63, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x61, 0x63, 0x63, 0x69, 0x64, 0x65, 0x6e, 0x74,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x61, 0x63, 0x63, 0x69, 0x64,
	0x65, 0x6e, 0x74, 0x49, 0x64, 0x32, 0x61, 0x0a, 0x0f, 0x41, 0x63, 0x63, 0x69, 0x64, 0x65, 0x6e,
	0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x4e, 0x0a, 0x12, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x41, 0x63, 0x63, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x44, 0x61, 0x74, 0x61, 0x12, 0x13,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x41, 0x63, 0x63, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x44,
	0x61, 0x74, 0x61, 0x1a, 0x21, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x41, 0x63, 0x63, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x3b, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_accident_proto_rawDescOnce sync.Once
	file_accident_proto_rawDescData = file_accident_proto_rawDesc
)

func file_accident_proto_rawDescGZIP() []byte {
	file_accident_proto_rawDescOnce.Do(func() {
		file_accident_proto_rawDescData = protoimpl.X.CompressGZIP(file_accident_proto_rawDescData)
	})
	return file_accident_proto_rawDescData
}

var file_accident_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_accident_proto_goTypes = []interface{}{
	(*AccidentData)(nil),               // 0: proto.AccidentData
	(*CreateAccidentDataResponse)(nil), // 1: proto.CreateAccidentDataResponse
	(*timestamp.Timestamp)(nil),        // 2: google.protobuf.Timestamp
}
var file_accident_proto_depIdxs = []int32{
	2, // 0: proto.AccidentData.time:type_name -> google.protobuf.Timestamp
	0, // 1: proto.AccidentService.CreateAccidentData:input_type -> proto.AccidentData
	1, // 2: proto.AccidentService.CreateAccidentData:output_type -> proto.CreateAccidentDataResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_accident_proto_init() }
func file_accident_proto_init() {
	if File_accident_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_accident_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AccidentData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_accident_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateAccidentDataResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_accident_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_accident_proto_goTypes,
		DependencyIndexes: file_accident_proto_depIdxs,
		MessageInfos:      file_accident_proto_msgTypes,
	}.Build()
	File_accident_proto = out.File
	file_accident_proto_rawDesc = nil
	file_accident_proto_goTypes = nil
	file_accident_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// AccidentServiceClient is the client API for AccidentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AccidentServiceClient interface {
	CreateAccidentData(ctx context.Context, in *AccidentData, opts ...grpc.CallOption) (*CreateAccidentDataResponse, error)
}

type accidentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAccidentServiceClient(cc grpc.ClientConnInterface) AccidentServiceClient {
	return &accidentServiceClient{cc}
}

func (c *accidentServiceClient) CreateAccidentData(ctx context.Context, in *AccidentData, opts ...grpc.CallOption) (*CreateAccidentDataResponse, error) {
	out := new(CreateAccidentDataResponse)
	err := c.cc.Invoke(ctx, "/proto.AccidentService/CreateAccidentData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AccidentServiceServer is the server API for AccidentService service.
type AccidentServiceServer interface {
	CreateAccidentData(context.Context, *AccidentData) (*CreateAccidentDataResponse, error)
}

// UnimplementedAccidentServiceServer can be embedded to have forward compatible implementations.
type UnimplementedAccidentServiceServer struct {
}

func (*UnimplementedAccidentServiceServer) CreateAccidentData(context.Context, *AccidentData) (*CreateAccidentDataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateAccidentData not implemented")
}

func RegisterAccidentServiceServer(s *grpc.Server, srv AccidentServiceServer) {
	s.RegisterService(&_AccidentService_serviceDesc, srv)
}

func _AccidentService_CreateAccidentData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccidentData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccidentServiceServer).CreateAccidentData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.AccidentService/CreateAccidentData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccidentServiceServer).CreateAccidentData(ctx, req.(*AccidentData))
	}
	return interceptor(ctx, in, info, handler)
}

var _AccidentService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.AccidentService",
	HandlerType: (*AccidentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateAccidentData",
			Handler:    _AccidentService_CreateAccidentData_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "accident.proto",
}
